buildpage and makepage no longer need args
buildpage still has bug:
>>> buildpage()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kybyz.py", line 194, in buildpage
  File "kybyz.py", line 56, in __new__
AttributeError: 'NoneType' object has no attribute 'attributes'